-- Denominations
INSERT INTO denominations(denomination_id,country_id,display_name,tags,series) VALUES("mex_libertad","mex","libertad","bullion","base");INSERT INTO denomination_names(denomination_id,name) VALUES("mex_libertad","libertad");INSERT INTO denomination_names(denomination_id,name) VALUES("mex_libertad","libertads");

-- Values
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_fractional_1_20_oz","mex_libertad",0.05,"1/20 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_fractional_1_10_oz","mex_libertad",0.1,"1/10 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_fractional_1_4_oz","mex_libertad",0.25,"1/4 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_fractional_1_2_oz","mex_libertad",0.5,"1/2 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_1_oz","mex_libertad",1,"1 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_2_oz","mex_libertad",2,"2 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_5_oz","mex_libertad",5,"5 oz libertad","base");
INSERT INTO face_values(value_id,denomination_id,value,display_name,series) VALUES("mex_libertad_1_kilogram","mex_libertad",32.15,"1 kilo libertad","base");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_20_oz","1/20");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_20_oz","1/20 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_20_oz","1/20 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_10_oz","1/10");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_10_oz","1/10 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_10_oz","1/10 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_4_oz","1/4");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_4_oz","1/4 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_4_oz","1/4 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_2_oz","1/2");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_2_oz","1/2 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_fractional_1_2_oz","1/2 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_oz","1");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_oz","1 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_oz","1 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_2_oz","2");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_2_oz","2 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_2_oz","2 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_5_oz","5");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_5_oz","5 oz");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_5_oz","5 oz libertad");

INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_kilogram","1");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_kilogram","1 kilo");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_kilogram","1 kilogram");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_kilogram","1 kilo libertad");
INSERT INTO face_values_names(value_id,name) VALUES("mex_libertad_1_kilogram","1 kilogram libertad");

-- Coins
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_20_oz_1","mex_libertad_fractional_1_20_oz",1.56,0.9999,0.0500,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_20_oz_2","mex_libertad_fractional_1_20_oz",1.56,0.9999,0.0500,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_10_oz_1","mex_libertad_fractional_1_10_oz",3.11,0.9999,0.1000,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_10_oz_2","mex_libertad_fractional_1_10_oz",3.11,0.9999,0.100,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_4_oz_1","mex_libertad_fractional_1_4_oz",8.67,0.9000,0.2500,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_4_oz_2","mex_libertad_fractional_1_4_oz",7.80,0.9999,0.2500,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_4_oz_3","mex_libertad_fractional_1_4_oz",7.80,0.9999,0.2500,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_4_oz_4","mex_libertad_fractional_1_4_oz",7.80,0.9999,0.2500,"pt","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_2_oz_1","mex_libertad_fractional_1_2_oz",17.29,0.9000,0.5000,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_2_oz_2","mex_libertad_fractional_1_2_oz",15.56,0.9999,0.5000,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_fractional_1_2_oz_3","mex_libertad_fractional_1_2_oz",15.56,0.9999,0.5000,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_1_oz_1","mex_libertad_1_oz",31.11,0.9999,1.0000,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_1_oz_2","mex_libertad_1_oz",34.56,0.9000,1.000,"au","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_1_oz_3","mex_libertad_1_oz",31.11,0.9999,1.000,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_2_oz_1","mex_libertad_2_oz",62.22,0.9999,2.000,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_5_oz_1","mex_libertad_5_oz",15.55,0.9999,5.000,"ag","base");
INSERT INTO coins(coin_id,face_value_id,gross_weight,fineness,precious_metal_weight,metal,series) VALUES("mex_libertad_1_kilogram_1","mex_libertad_1_kilogram",1000,0.9999,32.15,"ag","base");

-- Years
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_1", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_1", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_1",1981);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_2", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_1",1981);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_1",1989);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_2", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_1", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_2",1981);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_2",1983);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1",2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_kilogram_1", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_20_oz_2", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_10_oz_2", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3",1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_3", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_4_oz_4", 1989);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_fractional_1_2_oz_3", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1982);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1983);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1984);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1985);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1986);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1987);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1988);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1989);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1990);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1991);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1992);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1993);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1994);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1995);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_1_oz_3", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_2_oz_1", 2026);

INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 1996);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 1997);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 1998);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 1999);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2000);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2001);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2002);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2003);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2004);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2005);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2006);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2007);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2008);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2009);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2010);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2011);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2012);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2013);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2014);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2015);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2016);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2017);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2018);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2019);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2020);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2021);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2022);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2023);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2024);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2025);
INSERT INTO years(coin_id,year) VALUES("mex_libertad_5_oz_1", 2026);

UPDATE version set major=1, minor=1;
